var rand=0;
var checkList = new Array(230);
var previousValue='';

//creates the basic html
function menufullgame() {
document.getElementById('principal').innerHTML="<center><h1 id=nomeprinc><b>Full Games</b></h1><b><h2>Alex Kidd in Trouble</h2></b><img src='https://i.imgur.com/69kuPZp.gif' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/HZxpB5C-iuA width='500' height='300' frameborder='0'></iframe><br>Last Update: 18/07/16<br><a target='_blank' href=https://www.virustotal.com/gui/file/2341a2023a06dc548673fe3c3ef2b954abb1752a9c124627dea4ed3cb1a5ad6d/detection>Scan</a><br><input type=button onClick=window.open('https://www.dropbox.com/s/wueu530ny6iowdi/AlexKiddinTrouble.zip?dl=1','_blank') value='Download'><br><br><b><h2>Steel Warriors</h2></b><img src='https://i.imgur.com/0ySKxCz.gif' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/uYUYkkrVAVU width='500' height='300' frameborder='0'></iframe><br><table border=0 width=350><tr><td align=center><b>Ver 4</b><br>Last Update: 21/07/16<br><a target='_blank' href=https://www.virustotal.com/gui/url/169e9efc0b316c87e33c563aff1061b74793dcf91a241f97b0efc6e1b850ea9b/detection>Scan</a><br><input type=button onClick=window.open('https://www.dropbox.com/s/bisu7x0log6ld3b/MSW-Steel%20Warriors_V4.rar?dl=1','_blank') value='Download'><br>20/02/24<br><a target='_blank' href='https://drive.google.com/uc?id=1_ouH51Hy6SMdLdG3il9wtGeUeqndw1Z4'>Mikmod update</a><td align=center><b>Alpha V3</b><br><i>buggy</i><br><input type=button onClick=window.open('https://www.dropbox.com/s/yqj1o61uoc27otm/MSW-Steel%20Warriors_v3.rar?dl=1','_blank') value='Download'><td align=center><b>DEV_folder</b><br><input type=button onClick=window.open('https://drive.google.com/drive/folders/13LWwAOW8baxt1m460NKqNg0RB5nlSQNF?usp=drive_link','_blank') value='Access'><br><a target='_blank' href='PPC.html'>PPC</a><tr></table><br><br><b><h2>MugenKMK</h2></b><img src='https://i.imgur.com/yOgk2k3.png' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/h5k5G6Dt6ho width='500' height='300' frameborder='0'></iframe><br><input type=button onClick='createSelect()' value='Create select.def'><br><table border=0><tr><td align=left><span id=2></span></table><br><input type=button onclick='downloadFile()' id='btndown' value='download'><br><br></center>"
btnnew.disabled=false;
btnchar.disabled=false;
btnstg.disabled=false;
btnfullg.disabled=true;
btnyotu.disabled=false;
btndown.disabled=true;
}

function createSelect() {

checkList = [];
previousValue='<br>;Select.def randomly generated by<br>;https://mabskmk.github.io/<br><br>;Roster = 97<br>;Stock = 426<br>;Missing = 55+<br><br>[Characters]<br>randomselect<br>';

for (x=1;x<98;x++) {

	//Set a randomValue
	rand=(Math.floor(Math.random()*227)+1);
	
	//Compares with the check list
	while (checkList[rand]=='ok') {
	rand=(Math.floor(Math.random()*227)+1);
	}

	//Creates a line with randomValue index
	if (checkList[rand]!='ok') {
		checkList[rand]='ok';
		buildLine((rand),x);
	}
}
document.getElementById(2).innerHTML=""+previousValue+"<br>[ExtraStages]<br><br>[Options]<br>arcade.maxmatches = 10,0,0,0,0,0,0,0,0,0<br>team.maxmatches = 10,0,0,0,0,0,0,0,0,0<br>"
previousValue = document.getElementById(2).innerText;
btndown.disabled=false;
}

//Database
function buildLine(numero,cod) {
switch (numero) {
case 1:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='A-green.zip,stages/Abadox.def';}
	if (rand==1) {mydiv='Yuyuko.zip,stages/Abadox.def';}
break;
case 2:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Botan.zip,stages/AlexKiddInSW_Bossr1.def';}
	if (rand==1) {mydiv='Rin_Rin.zip,stages/AlexKiddInSW_Bossr1.def';} //***
break;
case 3:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gigi.zip,stages/AlexKiddInSW_Bossr3.def';}
	if (rand==1) {mydiv='Bishamon.zip,stages/AlexKiddInSW_Bossr3.def';}
break;
case 4:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='HattoriHanzo.zip,stages/AlexKiddInSW_Bossr4.def';}
	if (rand==1) {mydiv='Mr_Han.zip,stages/AlexKiddInSW_Bossr4.def';}
break;
case 5:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cheshire.zip,stages/AlexKiddInSW_Bossr9.def';}
	if (rand==1) {mydiv='Kini.zip,stages/AlexKiddInSW_Bossr9.def';}
break;
case 6:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Aisha.zip,stages/An_Hui.def';}
	if (rand==1) {mydiv='Raval.zip,stages/An_Hui.def';}
break;
case 7:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Benten.zip,stages/Analyzer.def';}
	if (rand==1) {mydiv='Benten.zip,stages/Analyzer.def';} //copy
break;
case 8:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Akaakiha.zip,stages/AncientShadows.def';}
	if (rand==1) {mydiv='Akaakiha.zip,stages/AncientShadows.def';} //copy
break;
case 9:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Mac_osx.zip,stages/androdunos-moon.def';}
	if (rand==1) {mydiv='SakiOmokane.zip,stages/androdunos-moon.def';}
break;
case 10:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Amingo.zip,stages/AngelIslandzone1.def';}
	if (rand==1) {mydiv='Zeldia.zip,stages/AngelIslandzone2.def';}
	if (rand==2) {mydiv='Mattrex.zip,stages/AngelIslandzone3.def';}
	if (rand==3) {mydiv='Zeldia.zip,stages/AngelIslandzone4.def';}
	if (rand==4) {mydiv='Zeldia.zip,stages/AngelIslandzone5.def';} //copy
break;
case 11:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cvs_Athena.zip,stages/AquaticRuins.def';}
	if (rand==1) {mydiv='Taros.zip,stages/AquaticRuins.def';}
break;
case 12:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Masako.zip,stages/ARENA.def';}
	if (rand==1) {mydiv='Deliza.zip,stages/ARENA.def';}
break;
case 13:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Goeniko6.zip,stages/ArkanoidSyn1.def';}
	if (rand==1) {mydiv='GodRugal.zip,stages/ArkanoidSyn2.def';}
	if (rand==2) {mydiv='A16.zip,stages/ArkanoidSyn3.def';}
	if (rand==3) {mydiv='Baiken_SLASH.zip,stages/ArkanoidSyn4.def';}
	if (rand==4) {mydiv='Kurokisi.zip,stages/ArkanoidSyn5.def';}
break;
case 14:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gracy.zip,stages/Axel_city.def';}
	if (rand==1) {mydiv='DrZan.zip,stages/Axel_city.def';}
break;
case 15:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rufuu.zip,stages/BattleZequeDen_Cave.def';}
	if (rand==1) {mydiv='Hong_Meirin.zip,stages/BattleZequeDen_Cave.def';}
break;
case 16:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Jagi.zip,stages/BayRoute.def';}
	if (rand==1) {mydiv='AXL.zip,stages/BayRoute.def';}
break;
case 17:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Wonder.zip,stages/BayYard1.def';}
	if (rand==1) {mydiv='Michelle_heart.zip,stages/BayYard2.def';}
	if (rand==2) {mydiv='RogueSp.zip,stages/BayYard3.def';}
break;
case 18:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sankuro.zip,stages/bc_ARGHBAR.def';}
	if (rand==1) {mydiv='Madruga.zip,stages/bc_ARGHBAR.def';}
break;
case 19:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gillius.zip,stages/bc_COLLAVA.def';}
	if (rand==1) {mydiv='EarthQuakeActSvC.zip,stages/bc_COLLAVA.def';}
break;
case 20:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Jentai.zip,stages/bc_CYCSTAGE1.def';}
	if (rand==1) {mydiv='Nayu.zip,stages/bc_CYCSTAGE2.def';}
break;
case 21:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Paladin.zip,stages/bc_KITSUNOH.def';}
	if (rand==1) {mydiv='Kenshin.zip,stages/bc_KITSUNOH.def';}
break;
case 22:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Pesoguin.zip,stages/bc_SYCHATCH.def';}
	if (rand==1) {mydiv='Sasquatch.zip,stages/bc_SYCHATCH.def';}
break;
case 23:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yoshitora.zip,stages/BronzeAuditorium.def';}
	if (rand==1) {mydiv='Yumeji.zip,stages/BronzeAuditorium.def';}
break;
case 24:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ayu.zip,stages/BurningArena.def';}
	if (rand==1) {mydiv='DragonClaw.zip,stages/BurningArena.def';}
break;
case 25:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Charlotte.zip,stages/BurningVillage.def';}
	if (rand==1) {mydiv='Warakia.zip,stages/BurningVillage.def';}
break;
case 26:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Deedrit.zip,stages/BusterSTG1.def';}
	if (rand==1) {mydiv='Elza.zip,stages/BusterSTG1.def';}
break;
case 27:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sally_gknux.zip,stages/BusterSTG2.def';}
	if (rand==1) {mydiv='AmyRose.zip,stages/BusterSTG2.def';}
break;
case 28:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='DaddySD.zip,stages/BusterSTG3.def';}
	if (rand==1) {mydiv='Zangia.zip,stages/BusterSTG3.def';}
break;
case 29:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Seiya.zip,stages/BusterSTG4.def';}
	if (rand==1) {mydiv='Ikki.zip,stages/BusterSTG4.def';}
break;
case 30:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Footee.zip,stages/BusterSTG5.def';}
	if (rand==1) {mydiv='Ryuho.zip,stages/BusterSTG5.def';}
break;
case 31:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='W_Len.zip,stages/BusterSTG6.def';}
	if (rand==1) {mydiv='Fliz.zip,stages/BusterSTG6.def';}
break;
case 32:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Flamme.zip,stages/BusterSTG7.def';}
	if (rand==1) {mydiv='Caulifla.zip,stages/BusterSTG7.def';}
break;
case 33:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sandra.zip,stages/BusterSTG8.def';}
	if (rand==1) {mydiv='Shera.zip,stages/BusterSTG8.def';}
break;
case 34:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Nyakko.zip,stages/Cat_RaceOTR.def';}
	if (rand==1) {mydiv='Neco-arc.zip,stages/Cat_RaceOTR.def';}
break;
case 35:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Owl.zip,stages/CDB1.def';}
	if (rand==1) {mydiv='Optimus.zip,stages/CDB2.def';}
break;
case 36:
	rand=(Math.floor(Math.random()*4));
	if (rand==0) {mydiv='CvsYoko.zip,stages/ChemicalPlant1.def';}
	if (rand==1) {mydiv='Roomi.zip,stages/ChemicalPlant2.def';}
	if (rand==2) {mydiv='Cvs_Mai.zip,stages/ChemicalPlant3.def';}
	if (rand==3) {mydiv='Xi_Lucy.zip,stages/ChemicalPlant4.def';}
break;
case 37:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Squall.zip,stages/chompman1.def';}
	if (rand==1) {mydiv='Slasher_Athena.zip,stages/chompman1.def';}
break;
case 38:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='FateCopy1.zip,stages/chompman2.def';}
	if (rand==1) {mydiv='FateCopy2.zip,stages/chompman2.def';}
break;
case 39:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Snake.zip,stages/chompman3.def';}
	if (rand==1) {mydiv='Meld.zip,stages/chompman3.def';}
break;
case 40:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='W_Taku.zip,stages/chompman4.def';}
	if (rand==1) {mydiv='Meteor.zip,stages/chompman4.def';}
break;
case 41:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='MvC_Samus.zip,stages/CiliaMonster.def';}
	if (rand==1) {mydiv='Shumag.zip,stages/CiliaMonster.def';}
break;
case 42:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Captain_Kebab.zip,stages/CKebabStg.def';}
	if (rand==1) {mydiv='Captain_Kebab.zip,stages/CKebabStg.def';} //copy*
break;
case 43:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Felicia.zip,stages/ClubMFG.def';}
	if (rand==1) {mydiv='PZ.zip,stages/ClubMFG.def';}
break;
case 44:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Aner.zip,stages/CocoronSKULL1.def';}
	if (rand==1) {mydiv='Aner_Rolange.zip,stages/CocoronSKULL1.def';}
	if (rand==2) {mydiv='Another_blood.zip,stages/CocoronSKULL2.def';}
break;
case 45:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Lilica.zip,stages/CollisionChaos.def';}
	if (rand==1) {mydiv='Aoi_Kusanagi.zip,stages/CollisionChaos.def';} //***
break;
case 46:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Arma.zip,stages/CosmoPG1.def';}
	if (rand==1) {mydiv='Shaia.zip,stages/CosmoPG1.def';}
break;
case 47:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BloodRayne_MVC.zip,stages/CosmoPG2.def';}
	if (rand==1) {mydiv='Isabeau.zip,stages/CosmoPG2.def';} //***
break;
case 48:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kingpa.zip,stages/CosmoPG3.def';}
	if (rand==1) {mydiv='Kingpa.zip,stages/CosmoPG3.def';} //copy
break;
case 49:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Panty_SB.zip,stages/CrazyWoods1.def';}
	if (rand==1) {mydiv='Stocking_SB.zip,stages/CrazyWoods1.def';}
break;
case 50:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kubota.zip,stages/CrazyWoods2.def';}
	if (rand==1) {mydiv='Yuuka.zip,stages/CrazyWoods2.def';}
break;
case 51:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kimberley.zip,stages/Crude-Buster1.def';}
	if (rand==1) {mydiv='Ralf_WLS.zip,stages/Crude-Buster1.def';}
break;
case 52:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Storm3.zip,stages/Crude-Buster2.def';}
	if (rand==1) {mydiv='Brolix.zip,stages/Crude-Buster2.def';}
break;
case 53:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Shiratama.zip,stages/Crude-Buster3.def';}
	if (rand==1) {mydiv='Potemkin.zip,stages/Crude-Buster3.def';}
break;
case 54:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Wolfang.zip,stages/Crude-Buster4.def';}
	if (rand==1) {mydiv='Ice.zip,stages/Crude-Buster4.def';}
break;
case 55:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Double-A.zip,stages/Crude-Buster5.def';}
	if (rand==1) {mydiv='Shiki.zip,stages/Crude-Buster5.def';}
break;
case 56:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Dcat_Krang.zip,stages/Crude-Buster6.def';}
	if (rand==1) {mydiv='Starscream.zip,stages/Crude-Buster6.def';}
break;
case 57:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Shizumaru.zip,stages/Cry-of-the-Spirits.def';}
	if (rand==1) {mydiv='Tsunade.zip,stages/Cry-of-the-Spirits.def';}
break;
case 58:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Xavier.zip,stages/CrystalForest.def';}
	if (rand==1) {mydiv='Alice-as.zip,stages/CrystalForest.def';}
break;
case 59:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Seoritsuhime.zip,stages/Cybernoid.def';}
	if (rand==1) {mydiv='Ukyo.zip,stages/Cybernoid.def';}
break;
case 60:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Nemesis.zip,stages/DarkForestKnytt.def';}
	if (rand==1) {mydiv='Unknown.zip,stages/DarkForestKnytt.def';}
break;
case 61:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='YuriAOF2.zip,stages/Deadmoon_stg1.def';}
	if (rand==1) {mydiv='Kuzira.zip,stages/Deadmoon_stg1.def';}
break;
case 62:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rolf.zip,stages/DeathStar3.def';}
	if (rand==1) {mydiv='Deathm.zip,stages/DeathStar3.def';}
break;
case 63:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Android18.zip,stages/DragladeDarth_Valley.def';}
	if (rand==1) {mydiv='Trunks.zip,stages/DragladeDarth_Valley.def';}
break;
case 64:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sg.zip,stages/Draglade_Ruins.def';}
	if (rand==1) {mydiv='Cable.zip,stages/Draglade_Ruins.def';}
break;
case 65:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Priest.zip,stages/DragladeUMA.def';}
	if (rand==1) {mydiv='Shaomu.zip,stages/DragladeUMA.def';}
break;
case 66:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='DrillAsamin.zip,stages/DrWilyStg1.def';}
	if (rand==1) {mydiv='Fubuki.zip,stages/DrWilyStg1.def';}
break;
case 67:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Metool.zip,stages/DrWilyStg2.def';}
	if (rand==1) {mydiv='Nbc_Hanzo.zip,stages/DrWilyStg2.def';}
break;
case 68:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Goku.zip,stages/DrWilyStg3.def';}
	if (rand==1) {mydiv='Goku.zip,stages/DrWilyStg3.def';} //copy
break;
case 69:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='GuillotineGen.zip,stages/DrWilyStg4.def';}
	if (rand==1) {mydiv='GuillotineGen.zip,stages/DrWilyStg4.def';} //copy
break;
case 70:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Brokken.zip,stages/DrWilyStg5.def';}
	if (rand==1) {mydiv='Private.zip,stages/DrWilyStg5.def';}
break;
case 71:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Robocop.zip,stages/EightmanStreet1.def';}
	if (rand==1) {mydiv='Robocain.zip,stages/EightmanStreet2.def';}
break;
case 72:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Fio.zip,stages/EquinoX_blue.def';}
	if (rand==1) {mydiv='Louis.zip,stages/EquinoX_blue.def';}
	if (rand==2) {mydiv='Piccolo.zip,stages/EquinoX_green.def';}
	if (rand==3) {mydiv='Zeus.zip,stages/EquinoX_green.def';}
	if (rand==4) {mydiv='Blackheart.zip,stages/EquinoX_red.def';}
break;
case 73:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Naruto.zip,stages/EscapeinaForest.def';}
	if (rand==1) {mydiv='Itachi.zip,stages/EscapeinaForest.def';}
break;
case 74:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ryu_Hoshi.zip,stages/FFstage.def';}
	if (rand==1) {mydiv='nbGouki.zip,stages/FFstage.def';}
break;
case 75:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Chargin_Chuck.zip,stages/FlappyBirdStg1.def';}
	if (rand==1) {mydiv='RinaOgata.zip,stages/FlappyBirdStg2.def';}
break;
case 76:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kracko.zip,stages/Fortress-of-Doom1.def';}
	if (rand==1) {mydiv='Kracko.zip,stages/Fortress-of-Doom1.def';} //copy
break;
case 77:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Chloe.zip,stages/Fortress-of-Doom2.def';}
	if (rand==1) {mydiv='Chloe.zip,stages/Fortress-of-Doom2.def';} //copy
break;
case 78:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Juri.zip,stages/Fortress-of-Doom3.def';}
	if (rand==1) {mydiv='Juri.zip,stages/Fortress-of-Doom3.def';} //copy
break;
case 79:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RajaaSion.zip,stages/Fortress-of-Doom4.def';}
	if (rand==1) {mydiv='RajaaMiyako.zip,stages/Fortress-of-Doom4.def';}
break;
case 80:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ProfessorX.zip,stages/Fuck3.def';}
	if (rand==1) {mydiv='ProfessorX.zip,stages/Fuck3.def';} //copy
break;
case 81:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Udonge_mb.zip,stages/Galactic-Night-Club.def';}
	if (rand==1) {mydiv='Marisa.zip,stages/Galactic-Night-Club.def';}
break;
case 82:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Azumi_Hojo.zip,stages/GanbareGoemon.def';}
	if (rand==1) {mydiv='Shinobu.zip,stages/GanbareGoemon.def';}
break;
case 83:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Garekky.zip,stages/garekkystg.def';}
	if (rand==1) {mydiv='Garekky.zip,stages/garekkystg.def';} //copy*
break;
case 84:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Cool.zip,stages/geno01.def';}
	if (rand==1) {mydiv='Zidane.zip,stages/geno02.def';}
	if (rand==2) {mydiv='Flynn.zip,stages/geno04.def';}
break;
case 85:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Han_Samuel.zip,stages/GHBlackBase1.def';}
	if (rand==1) {mydiv='Serena.zip,stages/GHBlackBase2.def';}
	if (rand==2) {mydiv='UndeadHero.zip,stages/GHBlackBase3.def';}
break;
case 86:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Donald.zip,stages/GHforcemine.def';}
	if (rand==1) {mydiv='Nameless.zip,stages/GHforcemine.def';} //***
break;
case 87:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Genkai.zip,stages/GHTheFinalAssault1A.def';}
	if (rand==1) {mydiv='Itigo.zip,stages/GHTheFinalAssault1B.def';}
break;
case 88:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Marina.zip,stages/GHTheFinalAssault2A.def';}
	if (rand==1) {mydiv='G-Silver.zip,stages/GHTheFinalAssault2B.def';}
break;
case 89:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='UBU.zip,stages/GoingThroughHell.def';}
	if (rand==1) {mydiv='UBU.zip,stages/GoingThroughHell.def';} //copy
break;
case 90:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Battle_Windows.zip,stages/GORN.def';}
	if (rand==1) {mydiv='Battle_Windows.zip,stages/GORN.def';} //copy
break;
case 91:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Tifa_z.zip,stages/Gourmet_Factory1.def';}
	if (rand==1) {mydiv='Lucia.zip,stages/Gourmet_Factory1.def';}
break;
case 92:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Catwoman.zip,stages/Gourmet_Factory2.def';}
	if (rand==1) {mydiv='Powergirl.zip,stages/Gourmet_Factory2.def';}
break;
case 93:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yungmie.zip,stages/Gourmet_Foot.def';}
	if (rand==1) {mydiv='Tung_RB.zip,stages/Gourmet_Foot.def';} //***
break;
case 94:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kula_new.zip,stages/Gourmet_Street1.def';}
	if (rand==1) {mydiv='Inma_z.zip,stages/Gourmet_Street2.def';}
break;
case 95:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ASH_AoD.zip,stages/Graveyard.def';}
	if (rand==1) {mydiv='Marrow.zip,stages/Graveyard.def';}
break;
case 96:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zaku.zip,stages/Greenbase.def';}
	if (rand==1) {mydiv='Blade.zip,stages/Greenbase.def';}
break;
case 97:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Mikaa.zip,stages/HazardBank.def';}
	if (rand==1) {mydiv='Swordsman.zip,stages/hazardbankC.def';} //***
break;
case 98:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Catherine-MVC.zip,stages/HazardTank.def';}
	if (rand==1) {mydiv='Super-8.zip,stages/HazardTank.def';} //***
break;
case 99:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='JessicaSmoke.zip,stages/HellGateB1.def';}
	if (rand==1) {mydiv='Kusaregedo.zip,stages/HellGateB50.def';}
	if (rand==2) {mydiv='Zemial.zip,stages/HellGateB100.def';}
break;
case 100:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SakuraW4rUGH.zip,stages/HiSpeedElevator1.def';}
	if (rand==1) {mydiv='SakuraW4rUGH.zip,stages/HiSpeedElevator2.def';} //copy
break;
case 101:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Petra.zip,stages/HomieYoshiStory1.def';}
	if (rand==1) {mydiv='Senna.zip,stages/HomieYoshiStory1.def';}
break;
case 102:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ryunmei.zip,stages/HomieYoshiStory2.def';}
	if (rand==1) {mydiv='Nanase.zip,stages/HomieYoshiStory2.def';}
break;
case 103:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Krystal.zip,stages/HomieYoshiStory3.def';}
	if (rand==1) {mydiv='Krystal.zip,stages/HomieYoshiStory3.def';} //copy
break;
case 104:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hiryu_SA.zip,stages/Hubei.def';}
	if (rand==1) {mydiv='Shishimaru.zip,stages/Hubei.def';}
break;
case 105:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Tamika.zip,stages/HuoChaiRen.def';}
	if (rand==1) {mydiv='Grendok.zip,stages/HuoChaiRen.def';}
break;
case 106:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Minis.zip,stages/IsamuGame5.def';}
	if (rand==1) {mydiv='C_mizuki.zip,stages/IsamuGame5.def';}
break;
case 107:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RubyHeart.zip,stages/IsamuGame7.def';}
	if (rand==1) {mydiv='Uozumi.zip,stages/IsamuGame7.def';}
break;
case 108:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cammysfm.zip,stages/Jiang_Xi_2.def';}
	if (rand==1) {mydiv='Jackie_DrunkenFist.zip,stages/Jiang_Xi_2.def';}
break;
case 109:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Centuriao.zip,stages/Jiii.def';}
	if (rand==1) {mydiv='WORM.zip,stages/Jiii.def';}
break;
case 110:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Vector.zip,stages/JungleZone.def';}
	if (rand==1) {mydiv='Chamcham.zip,stages/JungleZone.def';}
break;
case 111:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Dino.zip,stages/Jurassic_jungle.def';}
	if (rand==1) {mydiv='Dino.zip,stages/Jurassic_jungle.def';} //copy
break;
case 112:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='A-Shi.zip,stages/KirbyCourtyard.def';}
	if (rand==1) {mydiv='A-Shi.zip,stages/KirbyCourtyard.def';} //copy
break;
case 113:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ShangTsung.zip,stages/KirbyGoro.def';}
	if (rand==1) {mydiv='ShangTsung.zip,stages/KirbyGoro.def';} //copy
break;
case 114:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Raiden.zip,stages/KirbyPit.def';}
	if (rand==1) {mydiv='Raiden.zip,stages/KirbyPit.def';} //copy
break;
case 115:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rimle.zip,stages/KirbyPitsychedelic.def';}
	if (rand==1) {mydiv='Saber.zip,stages/KirbyPitsychedelic.def';}
break;
case 116:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Joseph2.zip,stages/LabyrinthZone.def';}
	if (rand==1) {mydiv='Redsnake.zip,stages/LabyrinthZone.def';}
break;
case 117:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Irriana.zip,stages/LastDungeon1.def';}
	if (rand==1) {mydiv='Lihua.zip,stages/LastDungeon2.def';}
break;
case 118:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ElmerDDR.zip,stages/Leventhan.def';}
	if (rand==1) {mydiv='Zeroko_w.zip,stages/Leventhan.def';}
break;
case 119:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Fefnir.zip,stages/Major_Release.def';}
	if (rand==1) {mydiv='Hayato.zip,stages/Major_Release.def';}
break;
case 120:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='MillarcaR-15.zip,stages/Majyuuou1.def';}
	if (rand==1) {mydiv='Riz.zip,stages/Majyuuou1.def';}
break;
case 121:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SMG_Jenny.zip,stages/Majyuuou2.def';}
	if (rand==1) {mydiv='SMG_Juni.zip,stages/Majyuuou2.def';}
break;
case 122:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ran_Yakumo.zip,stages/MechanicalFt.def';}
	if (rand==1) {mydiv='Ran_Yakumo.zip,stages/MechanicalFt.def';} //copy
break;
case 123:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zazel.zip,stages/Menace.def';}
	if (rand==1) {mydiv='Zazel.zip,stages/Menace.def';} //copy
break;
case 124:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='J_ignis.zip,stages/mETALgUN1.def';}
	if (rand==1) {mydiv='J_ignis.zip,stages/mETALgUN1.def';} //copy
break;
case 125:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Lelouch.zip,stages/mETALgUN2.def';}
	if (rand==1) {mydiv='Lelouch.zip,stages/mETALgUN2.def';} //copy
break;
case 126:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Athena-Police.zip,stages/MightyCity1.def';}
	if (rand==1) {mydiv='Solis.zip,stages/MightyCity1.def';}
break;
case 127:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Bertha.zip,stages/MightyCity2.def';}
	if (rand==1) {mydiv='Bertha.zip,stages/MightyCity2.def';} //copy
break;
case 128:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='zangyura.zip,stages/MiniCity.def';}
	if (rand==1) {mydiv='BOLT.zip,stages/MiniCity.def';}
break;
case 129:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='M_Burns.zip,stages/MM7_Graveyard.def';}
	if (rand==1) {mydiv='M_Burns.zip,stages/MM7_Graveyard.def';} //copy
break;
case 130:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Juggy.zip,stages/MN_bridge.def';}
	if (rand==1) {mydiv='TigreNegro.zip,stages/MN_bridge.def';}
break;
case 131:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Raiya.zip,stages/MN_roftop.def';}
	if (rand==1) {mydiv='Tetsu.zip,stages/MN_roftop.def';}
break;
case 132:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Abobo.zip,stages/MN_street.def';}
	if (rand==1) {mydiv='FatAlbert.zip,stages/MN_street.def';}
break;
case 133:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Lobo.zip,stages/MN_subway.def';}
	if (rand==1) {mydiv='Karl.zip,stages/MN_subway.def';}
break;
case 134:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ray.zip,stages/MN_truck.def';}
	if (rand==1) {mydiv='Ray.zip,stages/MN_truck.def';} //copy
break;
case 135:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Tia.zip,stages/MN_wharf.def';}
	if (rand==1) {mydiv='Yabuki.zip,stages/MN_wharf.def';}
break;
case 136:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Freedomnitori.zip,stages/MoaiRuin1.def';}
	if (rand==1) {mydiv='WingG.zip,stages/MoaiRuin1.def';}
break;
case 137:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yugi.zip,stages/MoaiRuin2.def';}
	if (rand==1) {mydiv='Yorihime.zip,stages/MoaiRuin2.def';}
break;
case 138:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Dios.zip,stages/MojoStronghold.def';}
	if (rand==1) {mydiv='Ikkyu.zip,stages/MojoStronghold.def';}
	if (rand==2) {mydiv='Amaterasu.zip,stages/MojoStronghold.def';}
break;
case 139:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Shouse.zip,stages/MonsterParty.def';}
	if (rand==1) {mydiv='Shouse.zip,stages/MonsterParty.def';} //copy
break;
case 140:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='mm_Franko.zip,stages/Musya.def';}
	if (rand==1) {mydiv='mm_Dink.zip,stages/Musya.def';}
break;
case 141:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='HIRO.zip,stages/MysticCave.def';}
	if (rand==1) {mydiv='HIRO.zip,stages/MysticCave.def';} //copy
break;
case 142:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Hikkoshi.zip,stages/MysticCaveRE1.def';}
	if (rand==1) {mydiv='Hikkoshi.zip,stages/MysticCaveRE2.def';}
	if (rand==2) {mydiv='Hikkoshi.zip,stages/MysticCaveRE3.def';} //copy
break;
case 143:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='<font color=red>Mika.zip,stages/Naga_Valley.def ;(R18)</font>';}
	if (rand==1) {mydiv='<font color=red>ShermieB.zip,stages/Naga_Valley.def ;(R18)</font>';}
	if (rand==2) {mydiv='<font color=red>Kasumi2.zip,stages/Naga_Valley.def ;(R18)</font>';}
	if (rand==3) {mydiv='<font color=red>NudeMary.zip,stages/Naga_Valley.def ;(R18)</font>';}
	if (rand==4) {mydiv='<font color=red>Xleona.zip,stages/Naga_Valley.def ;(R18)</font>';}
break;
case 144:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SoulGen.zip,stages/NamelessCity.def';}
	if (rand==1) {mydiv='Mileena.zip,stages/NamelessCity.def';}
break;
case 145:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Neon.zip,stages/NeonLight.def';}
	if (rand==1) {mydiv='Shorashah.zip,stages/NeonLight.def';}
break;
case 146:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sericha.zip,stages/NitD1.def';}
	if (rand==1) {mydiv='Serika.zip,stages/NitD1.def';}
break;
case 147:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='I-NO(GGXXR).zip,stages/NitD2.def';}
	if (rand==1) {mydiv='Neotabasa.zip,stages/NitD2.def';}
break;
case 148:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Vita.zip,stages/NitD3.def';}
	if (rand==1) {mydiv='Kogasa.zip,stages/NitD3.def';}
break;
case 149:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='LeiLeiPF.zip,stages/NitD4.def';}
	if (rand==1) {mydiv='Lei-Lei.zip,stages/NitD4.def';}
break;
case 150:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yukihime.zip,stages/NitD5.def';}
	if (rand==1) {mydiv='Kunagi.zip,stages/NitD5.def';}
break;
case 151:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Gradriel_O.zip,stages/NWcorridor1.def';}
	if (rand==1) {mydiv='Asura_[Dnf].zip,stages/NWcorridor2.def';}
	if (rand==2) {mydiv='Gradriel_O.zip,stages/NWcorridor3.def';} //copy
	if (rand==3) {mydiv='Asura_[Dnf].zip,stages/NWcorridor4.def';} //copy
	if (rand==4) {mydiv='Epyon.zip,stages/NWcorridorX.def';}
break;
case 152:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ultimate_Mizuki.zip,stages/NWparty.def';}
	if (rand==1) {mydiv='Moondragon.zip,stages/NWparty.def';}
break;
case 153:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rolento.zip,stages/OilOcean.def';}
	if (rand==1) {mydiv='S_Sinclair.zip,stages/OilOcean.def';}
break;
case 154:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='so_Blaze.zip,stages/PhantasyStarShip.def';}
	if (rand==1) {mydiv='Birdy.zip,stages/PhantasyStarShip.def';}
break;
case 155:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RazorClaws.zip,stages/PlanetPrision.def';}
	if (rand==1) {mydiv='Chrysalis.zip,stages/PlanetPrision.def';}
break;
case 156:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Wario2.zip,stages/Pok3dCave.def';}
	if (rand==1) {mydiv='Wario2.zip,stages/Pok3dValley.def';} //copy
break;
case 157:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kyndle.zip,stages/PsychoWasp.def';}
	if (rand==1) {mydiv='Kyndle.zip,stages/PsychoWasp.def';} //copy
break;
case 158:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Athena_Heidern.zip,stages/RadioMaze.def';}
	if (rand==1) {mydiv='Athena_nurse.zip,stages/RadioMaze.def';}
break;
case 159:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Spiral.zip,stages/RandomSpace.def';}
	if (rand==1) {mydiv='Mugena.zip,stages/RandomSpace.def';}
break;
case 160:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Tao.zip,stages/RanmaruSTG1.def';}
	if (rand==1) {mydiv='Kosanjou.zip,stages/RanmaruSTG1.def';}
break;
case 161:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cheng.zip,stages/RanmaruSTG2.def';}
	if (rand==1) {mydiv='Zerocvs.zip,stages/RanmaruSTG2.def';}
break;
case 162:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zantetsu.zip,stages/RescueGeisha.def';}
	if (rand==1) {mydiv='Kurenai.zip,stages/RescueGeisha.def';}
break;
case 163:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='MazingarZ.zip,stages/R-Factory.def';}
	if (rand==1) {mydiv='GMH.zip,stages/R-Factory.def';}
break;
case 164:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Angela_PI1.zip,stages/RInsanity.def';}
	if (rand==1) {mydiv='D.zip,stages/RInsanity.def';}
break;
case 165:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sieger.zip,stages/Rtype_Junkyard.def';}
	if (rand==1) {mydiv='Sieger.zip,stages/Rtype_Junkyard.def';} //copy
break;
case 166:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SilverSam.zip,stages/ScrapBrainZone.def';}
	if (rand==1) {mydiv='SilverSam.zip,stages/ScrapBrainZone.def';} //copy
break;
case 167:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rosemary.zip,stages/SecretVillage.def';}
	if (rand==1) {mydiv='Yagumo.zip,stages/SecretVillage.def';}
break;
case 168:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Steven_SeagalSnes,stages/ShaqFulab1.def';}
	if (rand==1) {mydiv='Jill.zip,stages/ShaqFulab2.def';}
	if (rand==2) {mydiv='H-Killer.zip,stages/ShaqFulab3.def';}
	if (rand==3) {mydiv='Rio.zip,stages/ShaqFulab4.def';}
	if (rand==4) {mydiv='Rax.zip,stages/ShaqFulab5.def';}
break;
case 169:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Femina30.zip,stages/ShockGalko.def';}
	if (rand==1) {mydiv='Femina32.zip,stages/ShockGalko.def';}
break;
case 170:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ruili.zip,stages/ShockTrain.def';}
	if (rand==1) {mydiv='Ruili.zip,stages/ShockTrain.def';} //copy
break;
case 171:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BebumRyo.zip,stages/Slightly_Mad.def';}
	if (rand==1) {mydiv='Eliza.zip,stages/Slightly_Mad.def';}
break;
case 172:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Barts.zip,stages/SlimSubwaySmash.def';}
	if (rand==1) {mydiv='Jack.zip,stages/SlimSubwaySmash.def';}
break;
case 173:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='EmmaFrost.zip,stages/SnowRush.def';}
	if (rand==1) {mydiv='EmmaFrost.zip,stages/SnowRush.def';} //copy
break;
case 174:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Doparmin.zip,stages/SonicBlastJet.def';}
	if (rand==1) {mydiv='Walkyrie.zip,stages/SonicBlastJet.def';}
break;
case 175:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hirezsonic.zip,stages/SonicSpecialStage.def';}
	if (rand==1) {mydiv='Hirezsonic.zip,stages/SonicSpecialStage.def';} //copy
break;
case 176:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Freedom.zip,stages/SpaceRocket.def';}
	if (rand==1) {mydiv='Freedom.zip,stages/SpaceRocket.def';} //copy
break;
case 177:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Renidagawa.zip,stages/Stage005.def';}
	if (rand==1) {mydiv='Gustavo.zip,stages/Stage005.def';}
break;
case 178:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cammy.zip,stages/stageCammy.def';}
	if (rand==1) {mydiv='so_Psycho.zip,stages/stageCammy.def';}
break;
case 179:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='CvsChunli.zip,stages/stageChunli.def';}
	if (rand==1) {mydiv='so_Dark.zip,stages/stageChunli.def';}
break;
case 180:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Ath-Chunli.zip,stages/stageDraco.def';}
	if (rand==1) {mydiv='Sexy_Arina.zip,stages/stageDraco.def';}
	if (rand==2) {mydiv='Hotaru_bikini.zip,stages/stageDraco.def';}
break;
case 181:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Lilica_Felchenerow.zip,stages/stageEtna.def';}
	if (rand==1) {mydiv='NACH03_MP-Suika.zip,stages/stageEtna.def';}
break;
case 182:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Grizela.zip,stages/stageGrizela.def';}
	if (rand==1) {mydiv='Grizela.zip,stages/stageGrizela.def';} //copy*
break;
case 183:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Harmir.zip,stages/stageHarmir.def';}
	if (rand==1) {mydiv='Harmir.zip,stages/stageHarmir.def';} //copy*
break;
case 184:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ORCHID.zip,stages/stageHumio.def';}
	if (rand==1) {mydiv='Elektra.zip,stages/stageHumio.def';}
break;
case 185:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Mako.zip,stages/stageMakoto.def';}
	if (rand==1) {mydiv='Mako.zip,stages/stageMakoto.def';} //copy
break;
case 186:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Aoko-ex.zip,stages/stageScharlachrot.def';}
	if (rand==1) {mydiv='Aoko-ex.zip,stages/stageScharlachrot.def';} //copy
break;
case 187:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zako-Dan.zip,stages/streetcombat_tyrone.def';}
	if (rand==1) {mydiv='Zako-Dan.zip,stages/streetcombat_tyrone.def';} //copy
break;
case 188:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zinc.zip,stages/SubSpace.def';}
	if (rand==1) {mydiv='Zinc.zip,stages/SubSpace.def';} //copy
break;
case 189:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Takezo.zip,stages/SubSpace1.def';}
	if (rand==1) {mydiv='Genpaku.zip,stages/SubSpace1.def';}
break;
case 190:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sailor_Mars.zip,stages/SubSpace2.def';}
	if (rand==1) {mydiv='Sailor_Jupiter.zip,stages/SubSpace2.def';}
break;
case 191:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yoma.zip,stages/SubSpace3.def';}
	if (rand==1) {mydiv='Maxine.zip,stages/SubSpace3.def';}
break;
case 192:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='mm_Paperguy.zip,stages/SubSpace4.def';}
	if (rand==1) {mydiv='Boon.zip,stages/SubSpace4.def';}
break;
case 193:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Bartman.zip,stages/SubSpace5.def';}
	if (rand==1) {mydiv='Manuel.zip,stages/SubSpace5.def';}
break;
case 194:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Raine.zip,stages/TailsAdventure1.def';}
	if (rand==1) {mydiv='Ranoh.zip,stages/TailsAdventure1.def';}
break;
case 195:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kongou.zip,stages/TailsAdventure2.def';}
	if (rand==1) {mydiv='Captain_Kido.zip,stages/TailsAdventure2.def';}
break;
case 196:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hashi.zip,stages/TerrariA.def';}
	if (rand==1) {mydiv='Peketo.zip,stages/TerrariA.def';}
break;
case 197:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Viuda_negra.zip,stages/TerrariB.def';}
	if (rand==1) {mydiv='Viuda_negra.zip,stages/TerrariB.def';} //copy
break;
case 198:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Shar-makai.zip,stages/TerrariC.def';}
	if (rand==1) {mydiv='Shar-makai.zip,stages/TerrariC.def';} //copy
break;
case 199:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gerdon.zip,stages/TerrorVision.def';}
	if (rand==1) {mydiv='Saya.zip,stages/TerrorVision.def';}
break;
case 200:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Mokou.zip,stages/The_Fire_Prominence.def';}
	if (rand==1) {mydiv='Mokou.zip,stages/The_Fire_Prominence.def';} //copy
break;
case 201:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Konata.zip,stages/TheRuinsofMetro.def';}
	if (rand==1) {mydiv='Yukari.zip,stages/TheRuinsofMetro.def';}
break;
case 202:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Predator_W.zip,stages/TitanForest.def';}
	if (rand==1) {mydiv='Predator_W.zip,stages/TitanForest.def';} //copy
break;
case 203:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Blockhead.zip,stages/TSTLoD.def';}
	if (rand==1) {mydiv='Biped.zip,stages/TSTLoD.def';}
break;
case 204:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ROBO-KY.zip,stages/TowerofMorgul.def';}
	if (rand==1) {mydiv='ROBO-JAM.zip,stages/TowerofMorgul.def';}
break;
case 205:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Asura_nbc.zip,stages/TowerofSuccubus.def';}
	if (rand==1) {mydiv='Chaos.zip,stages/TowerofSuccubus.def';}
break;
case 206:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='dc_Lion.zip,stages/Transilvania.def';}
	if (rand==1) {mydiv='Erim.zip,stages/Transilvania.def';}
break;
case 207:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Marco_nbc.zip,stages/TransporDrugs.def';}
	if (rand==1) {mydiv='Tarma.zip,stages/TransporTrain.def';}
	if (rand==2) {mydiv='Marco.zip,stages/TransporTrain.def';}
break;
case 208:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Athena_WPr.zip,stages/Typically_me.def';}
	if (rand==1) {mydiv='Ingrid.zip,stages/Typically_me.def';}
break;
case 209:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='DQ5-daughter.zip,stages/UluCity.def';}
	if (rand==1) {mydiv='DQ5-son.zip,stages/UluCityNF.def';}
break;
case 210:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cless.zip,stages/VegetableValley1.def';}
	if (rand==1) {mydiv='Kyle.zip,stages/VegetableValley2.def';}
break;
case 211:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RacingMiku2014_EV.zip,stages/Viotoxica1.def';}
	if (rand==1) {mydiv='RacingMiku2014_EV.zip,stages/Viotoxica1.def';} //copy
break;
case 212:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SvcAthenakof.zip,stages/Viotoxica2.def';}
	if (rand==1) {mydiv='Armor.zip,stages/Viotoxica2.def';}
break;
case 213:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='AOBA.zip,stages/Viotoxica3.def';}
	if (rand==1) {mydiv='Iari.zip,stages/Viotoxica3.def';}
break;
case 214:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Janne.zip,stages/Viotoxica4.def';}
	if (rand==1) {mydiv='Milan.zip,stages/Viotoxica4.def';}
break;
case 215:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BlackRockShooter.zip,stages/Viotoxica5.def';}
	if (rand==1) {mydiv='Minoriko-ONI.zip,stages/Viotoxica5.def';}
break;
case 216:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Aska-e.zip,stages/Weve-got-Shadowmans.def';}
	if (rand==1) {mydiv='VFKarin.zip,stages/Weve-got-Shadowmans.def';}
break;
case 217:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SMOke&CLaudia8b.zip,stages/WhisperForest1.def';}
	if (rand==1) {mydiv='Bbh.zip,stages/WhisperForest2.def';}
break;
case 218:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Fernando.zip,stages/WildSide.def';}
	if (rand==1) {mydiv='Pepito.zip,stages/WildSide.def';}
break;
case 219:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cell.zip,stages/Wolfchild2.def';}
	if (rand==1) {mydiv='Cell.zip,stages/Wolfchild2.def';} //copy
break;
case 220:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Carol.zip,stages/World_of_insanity.def';}
	if (rand==1) {mydiv='MAY_X.zip,stages/World_of_insanity.def';}
break;
case 221:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kurosawa.zip,stages/WotD.def';}
	if (rand==1) {mydiv='Trident.zip,stages/WotD.def';}
break;
case 222:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gaits.zip,stages/XGranada.def';}
	if (rand==1) {mydiv='Helion.zip,stages/XGranada.def,music=sound/XGranada2.mp3';}
break;
case 223:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kira.zip,stages/ZeroCastle1.def';}
	if (rand==1) {mydiv='Kira.zip,stages/ZeroCastle1.def';} //copy
break;
case 224:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Haohmaru.zip,stages/ZeroCastle2.def';}
	if (rand==1) {mydiv='mvc3_Reika.zip,stages/ZeroCastle2.def';}
break;
case 225:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hien.zip,stages/ZLeo_M1.def';}
	if (rand==1) {mydiv='Hiryuko.zip,stages/ZLeo_M1.def';}
break;
case 226:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kureha.zip,stages/ZookHero_1.def';}
	if (rand==1) {mydiv='Ageha.zip,stages/ZookHero_1.def';}
break;
case 227:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BurningCirno.zip,stages/ZookHero_2.def';}
	if (rand==1) {mydiv='BurningCirno.zip,stages/ZookHero_2.def';} //copy
break;
case 999:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='';}
	if (rand==1) {mydiv='';}
break;
case 0:
mydiv='...'
}
//Write line and cache the new value
document.getElementById(2).innerText=""+previousValue+""+mydiv+""
previousValue = document.getElementById(2).innerText + "<br>";
};

function downloadFile() {
 const link = document.createElement("a");
 const content = previousValue;
 const file = new Blob([content], { type: 'text/plain' });
 link.href = URL.createObjectURL(file);
 link.download = "select.def";
 link.click();
 URL.revokeObjectURL(link.href);
};
