var rand=0;
var checkList = new Array(230);
var previousValue='';

//creates the basic html
function menufullgame() {
document.getElementById('principal').innerHTML="<center><h1 id=nomeprinc><b>Full Games</b></h1><b><h2>Alex Kidd in Trouble</h2></b><img src='https://i.imgur.com/69kuPZp.gif' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/HZxpB5C-iuA width='500' height='300' frameborder='0'></iframe><br>Last Update: 18/07/16<br><a target='_blank' href=https://www.virustotal.com/gui/file/2341a2023a06dc548673fe3c3ef2b954abb1752a9c124627dea4ed3cb1a5ad6d/detection>Scan</a><br><input type=button onClick=window.open('https://www.dropbox.com/s/wueu530ny6iowdi/AlexKiddinTrouble.zip?dl=1','_blank') value='Download'><br><br><b><h2>Steel Warriors</h2></b><img src='https://i.imgur.com/0ySKxCz.gif' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/uYUYkkrVAVU width='500' height='300' frameborder='0'></iframe><br><table border=0 width=350><tr><td align=center><b>Ver 4</b><br>Last Update: 21/07/16<br><a target='_blank' href=https://www.virustotal.com/gui/url/169e9efc0b316c87e33c563aff1061b74793dcf91a241f97b0efc6e1b850ea9b/detection>Scan</a><br><input type=button onClick=window.open('https://www.dropbox.com/s/bisu7x0log6ld3b/MSW-Steel%20Warriors_V4.rar?dl=1','_blank') value='Download'><br>20/02/24<br><a target='_blank' href='https://drive.google.com/uc?id=1_ouH51Hy6SMdLdG3il9wtGeUeqndw1Z4'>Mikmod update</a><td align=center><b>Alpha V3</b><br><i>buggy</i><br><input type=button onClick=window.open('https://www.dropbox.com/s/yqj1o61uoc27otm/MSW-Steel%20Warriors_v3.rar?dl=1','_blank') value='Download'><td align=center><b>DEV_folder</b><br><input type=button onClick=window.open('https://drive.google.com/drive/folders/13LWwAOW8baxt1m460NKqNg0RB5nlSQNF?usp=drive_link','_blank') value='Access'><br><a target='_blank' href='PPC.html'>PPC</a><tr></table><br><br><b><h2>MugenKMK</h2></b><img src='https://i.imgur.com/yOgk2k3.png' width=75% height=75%><br><iframe src=https://www.youtube.com/embed/h5k5G6Dt6ho width='500' height='300' frameborder='0'></iframe><br><input type=button onClick='createSelect()' value='Create select.def'><br><table border=0 width=350><tr><td align=left><span id=2></span></table><br><input type=button onclick='downloadFile()' id='btndown' value='download'><br><br></center>"
btnnew.disabled=false;
btnchar.disabled=false;
btnstg.disabled=false;
btnfullg.disabled=true;
btnyotu.disabled=false;
btndown.disabled=true;
}

function createSelect() {

checkList = [];
previousValue='<br>;Select.def randomly generated by<br>;https://mabskmk.github.io/<br><br>[Characters]<br>randomselect<br>';

for (x=1;x<98;x++) {

	//Set a randomValue
	rand=(Math.floor(Math.random()*227)+1);
	
	//Compares with the check list
	while (checkList[rand]=='ok') {
	rand=(Math.floor(Math.random()*227)+1);
	}

	//Creates a line with randomValue index
	if (checkList[rand]!='ok') {
		checkList[rand]='ok';
		buildLine((rand),x);
	}
}
document.getElementById(2).innerHTML=""+previousValue+"<br>[ExtraStages]<br><br>[Options]<br>arcade.maxmatches = 10,0,0,0,0,0,0,0,0,0<br>team.maxmatches = 10,0,0,0,0,0,0,0,0,0<br>"
previousValue = document.getElementById(2).innerText;
btndown.disabled=false;
}

//Database
function buildLine(numero,cod) {
switch (numero) {
case 1:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yuyuko.zip,stages/Abadox.def';}
	if (rand==1) {mydiv='Yuyuko.zip,stages/Abadox.def';}
break;
case 2:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/AlexKiddInSW_Bossr1.def';}
	if (rand==1) {mydiv='?..........,stages/AlexKiddInSW_Bossr1.def';}
break;
case 3:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gigi.zip,stages/AlexKiddInSW_Bossr3.def';}
	if (rand==1) {mydiv='Gigi.zip,stages/AlexKiddInSW_Bossr3.def';}
break;
case 4:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='HattoriHanzo.zip,stages/AlexKiddInSW_Bossr4.def';}
	if (rand==1) {mydiv='HattoriHanzo.zip,stages/AlexKiddInSW_Bossr4.def';}
break;
case 5:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/AlexKiddInSW_Bossr9.def';}
	if (rand==1) {mydiv='?..........,stages/AlexKiddInSW_Bossr9.def';}
break;
case 6:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='aisha.zip,stages/An_Hui.def';}
	if (rand==1) {mydiv='raval.zip,stages/An_Hui.def';}
break;
case 7:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='benten.zip,stages/Analyzer.def';}
	if (rand==1) {mydiv='benten.zip,stages/Analyzer.def';}
break;
case 8:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Akaakiha.zip,stages/AncientShadows.def';}
	if (rand==1) {mydiv='Akaakiha.zip,stages/AncientShadows.def';}
break;
case 9:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='mac_osx.zip,stages/androdunos-moon.def';}
	if (rand==1) {mydiv='SakiOmokane.zip,stages/androdunos-moon.def';}
break;
case 10:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Zeldia.zip,stages/AngelIslandzone1.def';}
	if (rand==1) {mydiv='Zeldia.zip,stages/AngelIslandzone2.def';}
	if (rand==2) {mydiv='Zeldia.zip,stages/AngelIslandzone3.def';}
	if (rand==3) {mydiv='Zeldia.zip,stages/AngelIslandzone4.def';}
	if (rand==4) {mydiv='Zeldia.zip,stages/AngelIslandzone5.def';}
break;
case 11:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='cvs_Athena.zip,stages/AquaticRuins.def';}
	if (rand==1) {mydiv='cvs_Athena.zip,stages/AquaticRuins.def';}
break;
case 12:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='rena_r.zip,stages/ARENA.def';}
	if (rand==1) {mydiv='rena_r.zip,stages/ARENA.def';}
break;
case 13:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='?..........,stages/ArkanoidSyn1.def';}
	if (rand==1) {mydiv='?..........,stages/ArkanoidSyn2.def';}
	if (rand==2) {mydiv='a16.zip,stages/ArkanoidSyn3.def';}
	if (rand==3) {mydiv='?..........,stages/ArkanoidSyn4.def';}
	if (rand==4) {mydiv='baiken_SLASH.zip,stages/ArkanoidSyn5.def';}
break;
case 14:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='gracy.zip,stages/Axel_city.def';}
	if (rand==1) {mydiv='gracy.zip,stages/Axel_city.def';}
break;
case 15:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Rufuu.zip,stages/BattleZequeDen_Cave.def';}
	if (rand==1) {mydiv='Rufuu.zip,stages/BattleZequeDen_Cave.def';}
break;
case 16:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Jagi.zip,stages/BayRoute.def';}
	if (rand==1) {mydiv='Jagi.zip,stages/BayRoute.def';}
break;
case 17:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Wonder.zip,stages/BayYard1.def';}
	if (rand==1) {mydiv='michelle_heart.zip,stages/BayYard2.def';}
	if (rand==2) {mydiv='RogueSp.zip,stages/BayYard3.def';}
break;
case 18:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='sankuro.zip,stages/bc_ARGHBAR.def';}
	if (rand==1) {mydiv='sankuro.zip,stages/bc_ARGHBAR.def';}
break;
case 19:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Gillius.zip,stages/bc_COLLAVA.def';}
	if (rand==1) {mydiv='Gillius.zip,stages/bc_COLLAVA.def';}
break;
case 20:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/bc_CYCSTAGE1.def';}
	if (rand==1) {mydiv='nayu.zip,stages/bc_CYCSTAGE2.def';}
break;
case 21:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Paladin.zip,stages/bc_KITSUNOH.def';}
	if (rand==1) {mydiv='Paladin.zip,stages/bc_KITSUNOH.def';}
break;
case 22:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Pesoguin.zip,stages/bc_SYCHATCH.def';}
	if (rand==1) {mydiv='Pesoguin.zip,stages/bc_SYCHATCH.def';}
break;
case 23:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yoshitora.zip,stages/BronzeAuditorium.def';}
	if (rand==1) {mydiv='Yumeji.zip,stages/BronzeAuditorium.def';}
break;
case 24:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BurningArena.def';}
	if (rand==1) {mydiv='?..........,stages/BurningArena.def';}
break;
case 25:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='charlotte.zip,stages/BurningVillage.def';}
	if (rand==1) {mydiv='warakia.zip,stages/BurningVillage.def';}
break;
case 26:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG1.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG1.def';}
break;
case 27:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG2.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG2.def';}
break;
case 28:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG3.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG3.def';}
break;
case 29:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG4.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG4.def';}
break;
case 30:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG5.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG5.def';}
break;
case 31:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG6.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG6.def';}
break;
case 32:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG7.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG7.def';}
break;
case 33:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/BusterSTG8.def';}
	if (rand==1) {mydiv='?..........,stages/BusterSTG8.def';}
break;
case 34:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='nyakko.zip,stages/Cat_RaceOTR.def';}
	if (rand==1) {mydiv='nyakko.zip,stages/Cat_RaceOTR.def';}
break;
case 35:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='owl.zip,stages/CDB1.def';}
	if (rand==1) {mydiv='optimus.zip,stages/CDB2.def';}
break;
case 36:
	rand=(Math.floor(Math.random()*4));
	if (rand==0) {mydiv='cvsyoko.zip,stages/ChemicalPlant1.def';}
	if (rand==1) {mydiv='?..........,stages/ChemicalPlant2.def';}
	if (rand==2) {mydiv='cvs_Mai.zip,stages/ChemicalPlant3.def';}
	if (rand==3) {mydiv='xi_lucy.zip,stages/ChemicalPlant4.def';}
break;
case 37:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='squall.zip,stages/chompman1.def';}
	if (rand==1) {mydiv='Slasher_Athena.zip,stages/chompman1.def';}
break;
case 38:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/chompman2.def';}
	if (rand==1) {mydiv='?..........,stages/chompman2.def';}
break;
case 39:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Snake.zip,stages/chompman3.def';}
	if (rand==1) {mydiv='Meld.zip,stages/chompman3.def';}
break;
case 40:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Meteor.zip,stages/chompman4.def';}
	if (rand==1) {mydiv='Meteor.zip,stages/chompman4.def';}
break;
case 41:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/CiliaMonster.def';}
	if (rand==1) {mydiv='?..........,stages/CiliaMonster.def';}
break;
case 42:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Captain_Kebab.zip,stages/CKebabStg.def';}
	if (rand==1) {mydiv='Captain_Kebab.zip,stages/CKebabStg.def';}
break;
case 43:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='felicia.zip,stages/ClubMFG.def';}
	if (rand==1) {mydiv='pz.zip,stages/ClubMFG.def';}
break;
case 44:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Aner.zip,stages/CocoronSKULL1.def';}
	if (rand==1) {mydiv='Aner_Rolange.zip,stages/CocoronSKULL1.def';}
	if (rand==2) {mydiv='another_blood.zip,stages/CocoronSKULL2.def';}
break;
case 45:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='lilica.zip,stages/CollisionChaos.def';}
	if (rand==1) {mydiv='lilica.zip,stages/CollisionChaos.def';}
break;
case 46:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Arma.zip,stages/CosmoPG1.def';}
	if (rand==1) {mydiv='Arma.zip,stages/CosmoPG1.def';}
break;
case 47:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BloodRayne_MVC.zip,stages/CosmoPG2.def';}
	if (rand==1) {mydiv='BloodRayne_MVC.zip,stages/CosmoPG2.def';}
break;
case 48:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kingpa.zip,stages/CosmoPG3.def';}
	if (rand==1) {mydiv='kingpa.zip,stages/CosmoPG3.def';}
break;
case 49:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Panty_SB.zip,stages/CrazyWoods1.def';}
	if (rand==1) {mydiv='Panty_SB.zip,stages/CrazyWoods1.def';}
break;
case 50:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/CrazyWoods2.def';}
	if (rand==1) {mydiv='?..........,stages/CrazyWoods2.def';}
break;
case 51:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kimberley.zip,stages/Crude-Buster1.def';}
	if (rand==1) {mydiv='kimberley.zip,stages/Crude-Buster1.def';}
break;
case 52:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Storm3.zip,stages/Crude-Buster2.def';}
	if (rand==1) {mydiv='Storm3.zip,stages/Crude-Buster2.def';}
break;
case 53:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Crude-Buster3.def';}
	if (rand==1) {mydiv='?..........,stages/Crude-Buster3.def';}
break;
case 54:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Crude-Buster4.def';}
	if (rand==1) {mydiv='?..........,stages/Crude-Buster4.def';}
break;
case 55:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Shiratama.zip,stages/Crude-Buster5.def';}
	if (rand==1) {mydiv='Shiratama.zip,stages/Crude-Buster5.def';}
break;
case 56:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Crude-Buster6.def';}
	if (rand==1) {mydiv='?..........,stages/Crude-Buster6.def';}
break;
case 57:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='shizumaru.zip,stages/Cry-of-the-Spirits.def';}
	if (rand==1) {mydiv='shizumaru.zip,stages/Cry-of-the-Spirits.def';}
case 58:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='xavier.zip,stages/CrystalForest.def';}
	if (rand==1) {mydiv='alice-as.zip,stages/CrystalForest.def';}
break;
case 59:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='seoritsuhime.zip,stages/Cybernoid.def';}
	if (rand==1) {mydiv='seoritsuhime.zip,stages/Cybernoid.def';}
break;
case 60:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Nemesis.zip,stages/DarkForestKnytt.def';}
	if (rand==1) {mydiv='Nemesis.zip,stages/DarkForestKnytt.def';}
break;
case 61:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='YuriAOF2.zip,stages/Deadmoon_stg1.def';}
	if (rand==1) {mydiv='kuzira.zip,stages/Deadmoon_stg1.def';}
break;
case 62:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='rolf.zip,stages/DeathStar3.def';}
	if (rand==1) {mydiv='rolf.zip,stages/DeathStar3.def';}
break;
case 63:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='trunks.zip,stages/DragladeDarth_Valley.def';}
	if (rand==1) {mydiv='trunks.zip,stages/DragladeDarth_Valley.def';}
break;
case 64:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Draglade_Ruins.def';}
	if (rand==1) {mydiv='?..........,stages/Draglade_Ruins.def';}
break;
case 65:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/DragladeUMA.def';}
	if (rand==1) {mydiv='?..........,stages/DragladeUMA.def';}
break;
case 66:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/DrWilyStg1.def';}
	if (rand==1) {mydiv='?..........,stages/DrWilyStg1.def';}
break;
case 67:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='metool.zip,stages/DrWilyStg2.def';}
	if (rand==1) {mydiv='metool.zip,stages/DrWilyStg2.def';}
break;
case 68:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/DrWilyStg3.def';}
	if (rand==1) {mydiv='?..........,stages/DrWilyStg3.def';}
break;
case 69:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/DrWilyStg4.def';}
	if (rand==1) {mydiv='?..........,stages/DrWilyStg4.def';}
break;
case 70:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='brokken.zip,stages/DrWilyStg5.def';}
	if (rand==1) {mydiv='brokken.zip,stages/DrWilyStg5.def';}
break;
case 71:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/EightmanStreet1.def';}
	if (rand==1) {mydiv='?..........,stages/EightmanStreet2.def';}
break;
case 72:
	rand=(Math.floor(Math.random()*4));
	if (rand==0) {mydiv='fio.zip,stages/EquinoX_blue.def';}
	if (rand==1) {mydiv='louis.zip,stages/EquinoX_blue.def';}
	if (rand==2) {mydiv='zeus.zip,stages/EquinoX_green.def';}
	if (rand==3) {mydiv='Blackheart.zip,stages/EquinoX_red.def';}
break;
case 73:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/EscapeinaForest.def';}
	if (rand==1) {mydiv='?..........,stages/EscapeinaForest.def';}
break;
case 74:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ryu_Hoshi.zip,stages/FFstage.def';}
	if (rand==1) {mydiv='Ryu_Hoshi.zip,stages/FFstage.def';}
break;
case 75:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/FlappyBirdStg1.def';}
	if (rand==1) {mydiv='RinaOgata.zip,stages/FlappyBirdStg2.def';}
break;
case 76:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Fortress-of-Doom1.def';}
	if (rand==1) {mydiv='?..........,stages/Fortress-of-Doom1.def';}
break;
case 77:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Chloe&maumau.zip,stages/Fortress-of-Doom2.def';}
	if (rand==1) {mydiv='Chloe&maumau.zip,stages/Fortress-of-Doom2.def';}
break;
case 78:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='juri.zip,stages/Fortress-of-Doom3.def';}
	if (rand==1) {mydiv='juri.zip,stages/Fortress-of-Doom3.def';}
break;
case 79:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RajaaSion.zip,stages/Fortress-of-Doom4.def';}
	if (rand==1) {mydiv='RajaaSion.zip,stages/Fortress-of-Doom4.def';}
break;
case 80:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Fuck3.def';}
	if (rand==1) {mydiv='?..........,stages/Fuck3.def';}
break;
case 81:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='udonge_mb.zip,stages/Galactic-Night-Club.def';}
	if (rand==1) {mydiv='udonge_mb.zip,stages/Galactic-Night-Club.def';}
break;
case 82:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Azumi_Hojo.zip,stages/GanbareGoemon.def';}
	if (rand==1) {mydiv='Azumi_Hojo.zip,stages/GanbareGoemon.def';}
break;
case 83:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Garekky.zip,stages/garekkystg.def';}
	if (rand==1) {mydiv='Garekky.zip,stages/garekkystg.def';}
break;
case 84:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Cool.zip,stages/geno01.def';}
	if (rand==1) {mydiv='?..........,stages/geno02.def';}
	if (rand==2) {mydiv='?..........,stages/geno04.def';}
break;
case 85:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Han_Samuel.zip,stages/GHBlackBase1.def';}
	if (rand==1) {mydiv='Serena.zip,stages/GHBlackBase2.def';}
	if (rand==2) {mydiv='UndeadHero.zip,stages/GHBlackBase3.def';}
break;
case 86:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Donald.zip,stages/GHforcemine.def';}
	if (rand==1) {mydiv='Donald.zip,stages/GHforcemine.def';}
break;
case 87:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Genkai.zip,stages/GHTheFinalAssault1A.def';}
	if (rand==1) {mydiv='?..........,stages/GHTheFinalAssault1B.def';}
break;
case 88:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/GHTheFinalAssault2A.def';}
	if (rand==1) {mydiv='G-Silver.zip,stages/GHTheFinalAssault2B.def';}
break;
case 89:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='UBU.zip,stages/GoingThroughHell.def';}
	if (rand==1) {mydiv='UBU.zip,stages/GoingThroughHell.def';}
break;
case 90:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/GORN.def';}
	if (rand==1) {mydiv='?..........,stages/GORN.def';}
break;
case 91:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='tifa_z.zip,stages/Gourmet_Factory1.def';}
	if (rand==1) {mydiv='tifa_z.zip,stages/Gourmet_Factory1.def';}
break;
case 92:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='powergirl.zip,stages/Gourmet_Factory2.def';}
	if (rand==1) {mydiv='powergirl.zip,stages/Gourmet_Factory2.def';}
break;
case 93:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='lucia.zip,stages/Gourmet_Foot.def';}
	if (rand==1) {mydiv='lucia.zip,stages/Gourmet_Foot.def';}
break;
case 94:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Inma_z.zip,stages/Gourmet_Street1.def';}
	if (rand==1) {mydiv='Inma_z.zip,stages/Gourmet_Street2.def';}
break;
case 95:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Graveyard.def';}
	if (rand==1) {mydiv='?..........,stages/Graveyard.def';}
break;
case 96:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Greenbase.def';}
	if (rand==1) {mydiv='?..........,stages/Greenbase.def';}
break;
case 97:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Mikaa.zip,stages/HazardBank.def';}
	if (rand==1) {mydiv='?..........,stages/hazardbankC.def';}
break;
case 98:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Catherine-MVC.zip,stages/HazardTank.def';}
	if (rand==1) {mydiv='Catherine-MVC.zip,stages/HazardTank.def';}
break;
case 99:
	rand=(Math.floor(Math.random()*4));
	if (rand==0) {mydiv='?..........,stages/HellGateB1.def';}
	if (rand==1) {mydiv='kusaregedo.zip,stages/HellGateB50.def';}
	if (rand==2) {mydiv='zemial.zip,stages/HellGateB100.def';}
	if (rand==3) {mydiv=';Leopaldon.zip,stages/HellGateB100.def';}
break;
case 100:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SakuraW4rUGH.zip,stages/HiSpeedElevator1.def';}
	if (rand==1) {mydiv='SakuraW4rUGH.zip,stages/HiSpeedElevator2.def';}
break;
case 101:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/HomieYoshiStory1.def';}
	if (rand==1) {mydiv='?..........,stages/HomieYoshiStory1.def';}
break;
case 102:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/HomieYoshiStory2.def';}
	if (rand==1) {mydiv='?..........,stages/HomieYoshiStory2.def';}
break;
case 103:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='krystal.zip,stages/HomieYoshiStory3.def';}
	if (rand==1) {mydiv='krystal.zip,stages/HomieYoshiStory3.def';}
break;
case 104:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hiryu_SA.zip,stages/Hubei.def';}
	if (rand==1) {mydiv='Shishimaru.zip,stages/Hubei.def';}
break;
case 105:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='tamika.zip,stages/HuoChaiRen.def';}
	if (rand==1) {mydiv='grendok.zip,stages/HuoChaiRen.def';}
break;
case 106:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/IsamuGame5.def';}
	if (rand==1) {mydiv='?..........,stages/IsamuGame5.def';}
break;
case 107:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/IsamuGame7.def';}
	if (rand==1) {mydiv='?..........,stages/IsamuGame7.def';}
break;
case 108:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='cammysfm.zip,stages/Jiang_Xi_2.def';}
	if (rand==1) {mydiv='Jackie_DrunkenFist.zip,stages/Jiang_Xi_2.def';}
break;
case 109:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Jiii.def';}
	if (rand==1) {mydiv='?..........,stages/Jiii.def';}
break;
case 110:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/JungleZone.def';}
	if (rand==1) {mydiv='?..........,stages/JungleZone.def';}
break;
case 111:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='dino.zip,stages/Jurassic_jungle.def';}
	if (rand==1) {mydiv='dino.zip,stages/Jurassic_jungle.def';}
break;
case 112:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/KirbyCourtyard.def';}
	if (rand==1) {mydiv='?..........,stages/KirbyCourtyard.def';}
break;
case 113:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ShangTsung.zip,stages/KirbyGoro.def';}
	if (rand==1) {mydiv='ShangTsung.zip,stages/KirbyGoro.def';}
break;
case 114:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='raiden.zip,stages/KirbyPit.def';}
	if (rand==1) {mydiv='raiden.zip,stages/KirbyPit.def';}
break;
case 115:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/KirbyPitsychedelic.def';}
	if (rand==1) {mydiv='?..........,stages/KirbyPitsychedelic.def';}
break;
case 116:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='redsnake.zip,stages/LabyrinthZone.def';}
	if (rand==1) {mydiv='redsnake.zip,stages/LabyrinthZone.def';}
break;
case 117:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Irriana.zip,stages/LastDungeon1.def';}
	if (rand==1) {mydiv='lihua.zip,stages/LastDungeon2.def';}
break;
case 118:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Leventhan.def';}
	if (rand==1) {mydiv='?..........,stages/Leventhan.def';}
break;
case 119:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Major_Release.def';}
	if (rand==1) {mydiv='?..........,stages/Major_Release.def';}
break;
case 120:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='MillarcaR-15.zip,stages/Majyuuou1.def';}
	if (rand==1) {mydiv='Riz.zip,stages/Majyuuou1.def';}
break;
case 121:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SMG_Jenny.zip,stages/Majyuuou2.def';}
	if (rand==1) {mydiv='SMG_Jenny.zip,stages/Majyuuou2.def';}
break;
case 122:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ran_Yakumo.zip,stages/MechanicalFt.def';}
	if (rand==1) {mydiv='Ran_Yakumo.zip,stages/MechanicalFt.def';}
break;
case 123:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Menace.def';}
	if (rand==1) {mydiv='?..........,stages/Menace.def';}
break;
case 124:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='J_ignis.zip,stages/mETALgUN1.def';}
	if (rand==1) {mydiv='J_ignis.zip,stages/mETALgUN1.def';}
break;
case 125:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='lelouch.zip,stages/mETALgUN2.def';}
	if (rand==1) {mydiv='lelouch.zip,stages/mETALgUN2.def';}
break;
case 126:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Athena-Police.zip,stages/MightyCity1.def';}
	if (rand==1) {mydiv='Athena-Police.zip,stages/MightyCity1.def';}
break;
case 127:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/MightyCity2.def';}
	if (rand==1) {mydiv='?..........,stages/MightyCity2.def';}
break;
case 128:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='zangyura.zip,stages/MiniCity.def';}
	if (rand==1) {mydiv='BOLT.zip,stages/MiniCity.def';}
break;
case 129:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='M_Burns.zip,stages/MM7_Graveyard.def';}
	if (rand==1) {mydiv='M_Burns.zip,stages/MM7_Graveyard.def';}
break;
case 130:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/MN_bridge.def';}
	if (rand==1) {mydiv='?..........,stages/MN_bridge.def';}
break;
case 131:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='raiya.zip,stages/MN_roftop.def';}
	if (rand==1) {mydiv='raiya.zip,stages/MN_roftop.def';}
break;
case 132:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='abobo.zip,stages/MN_street.def';}
	if (rand==1) {mydiv='abobo.zip,stages/MN_street.def';}
break;
case 133:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Lobo.zip,stages/MN_subway.def';}
	if (rand==1) {mydiv='Lobo.zip,stages/MN_subway.def';}
break;
case 134:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ray.zip,stages/MN_truck.def';}
	if (rand==1) {mydiv='ray.zip,stages/MN_truck.def';}
break;
case 135:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='tia.zip,stages/MN_wharf.def';}
	if (rand==1) {mydiv='tia.zip,stages/MN_wharf.def';}
break;
case 136:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Freedomnitori.zip,stages/MoaiRuin1.def';}
	if (rand==1) {mydiv='Freedomnitori.zip,stages/MoaiRuin1.def';}
break;
case 137:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='yugi.zip,stages/MoaiRuin2.def';}
	if (rand==1) {mydiv='yugi.zip,stages/MoaiRuin2.def';}
break;
case 138:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ikkyu.zip,stages/MojoStronghold.def';}
	if (rand==1) {mydiv='ikkyu.zip,stages/MojoStronghold.def';}
break;
case 139:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='shouse.zip,stages/MonsterParty.def';}
	if (rand==1) {mydiv='shouse.zip,stages/MonsterParty.def';}
break;
case 140:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='UKYO.zip,stages/Musya.def';}
	if (rand==1) {mydiv='UKYO.zip,stages/Musya.def';}
break;
case 141:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='HIRO.zip,stages/MysticCave.def';}
	if (rand==1) {mydiv='HIRO.zip,stages/MysticCave.def';}
break;
case 142:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='hikkoshi.zip,stages/MysticCaveRE1.def';}
	if (rand==1) {mydiv='hikkoshi.zip,stages/MysticCaveRE2.def';}
	if (rand==2) {mydiv='hikkoshi.zip,stages/MysticCaveRE3.def';}
break;
case 143:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='janne.zip,stages/Naga_Valley.def';}
	if (rand==1) {mydiv='Milan.zip,stages/Naga_Valley.def';}
break;
case 144:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SoulGen.zip,stages/NamelessCity.def';}
	if (rand==1) {mydiv='SoulGen.zip,stages/NamelessCity.def';}
break;
case 145:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Neon.zip,stages/NeonLight.def';}
	if (rand==1) {mydiv='Neon.zip,stages/NeonLight.def';}
break;
case 146:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='sericha.zip,stages/NitD1.def';}
	if (rand==1) {mydiv='serika.zip,stages/NitD1.def';}
break;
case 147:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='I-NO(GGXXR).zip,stages/NitD2.def';}
	if (rand==1) {mydiv='neotabasa.zip,stages/NitD2.def';}
break;
case 148:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Haruhi.zip,stages/NitD3.def';}
	if (rand==1) {mydiv='Vita.zip,stages/NitD3.def';}
break;
case 149:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='LeiLeiPF.zip,stages/NitD4.def';}
	if (rand==1) {mydiv='Lei-Lei.zip,stages/NitD4.def';}
break;
case 150:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Yukihime.zip,stages/NitD5.def';}
	if (rand==1) {mydiv='kunagi.zip,stages/NitD5.def';}
break;
case 151:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='Gradriel_O.zip,stages/NWcorridor1.def';}
	if (rand==1) {mydiv='Asura_[Dnf].zip,stages/NWcorridor2.def';}
	if (rand==2) {mydiv='Gradriel_O.zip,stages/NWcorridor3.def';}
	if (rand==3) {mydiv='Asura_[Dnf].zip,stages/NWcorridor4.def';}
	if (rand==4) {mydiv='Gradriel_O.zip,stages/NWcorridorX.def';}
break;
case 152:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Ultimate_Mizuki.zip,stages/NWparty.def';}
	if (rand==1) {mydiv='Ultimate_Mizuki.zip,stages/NWparty.def';}
break;
case 153:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='rolento.zip,stages/OilOcean.def';}
	if (rand==1) {mydiv='S_Sinclair.zip,stages/OilOcean.def';}
break;
case 154:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='so_blaze.zip,stages/PhantasyStarShip.def';}
	if (rand==1) {mydiv='so_blaze.zip,stages/PhantasyStarShip.def';}
break;
case 155:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RazorClaws.zip,stages/PlanetPrision.def';}
	if (rand==1) {mydiv='Chrysalis.zip,stages/PlanetPrision.def';}
break;
case 156:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/Pok3dCave.def';}
	if (rand==1) {mydiv='?..........,stages/Pok3dValley.def';}
break;
case 157:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kyndle.zip,stages/PsychoWasp.def';}
	if (rand==1) {mydiv='kyndle.zip,stages/PsychoWasp.def';}
break;
case 158:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='athena_heidern.zip,stages/RadioMaze.def';}
	if (rand==1) {mydiv='athena_heidern.zip,stages/RadioMaze.def';}
break;
case 159:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='spiral.zip,stages/RandomSpace.def';}
	if (rand==1) {mydiv='spiral.zip,stages/RandomSpace.def';}
break;
case 160:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='tao.zip,stages/RanmaruSTG1.def';}
	if (rand==1) {mydiv='tao.zip,stages/RanmaruSTG1.def';}
break;
case 161:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cheng.zip,stages/RanmaruSTG2.def';}
	if (rand==1) {mydiv='Cheng.zip,stages/RanmaruSTG2.def';}
break;
case 162:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='zantetsu.zip,stages/RescueGeisha.def';}
	if (rand==1) {mydiv='zantetsu.zip,stages/RescueGeisha.def';}
break;
case 163:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='GMH.zip,stages/R-Factory.def';}
	if (rand==1) {mydiv='GMH.zip,stages/R-Factory.def';}
break;
case 164:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Angela_PI1.zip,stages/RInsanity.def';}
	if (rand==1) {mydiv='Angela_PI1.zip,stages/RInsanity.def';}
break;
case 165:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sieger.zip,stages/Rtype_Junkyard.def';}
	if (rand==1) {mydiv='Sieger.zip,stages/Rtype_Junkyard.def';}
break;
case 166:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='silversam.zip,stages/ScrapBrainZone.def';}
	if (rand==1) {mydiv='silversam.zip,stages/ScrapBrainZone.def';}
break;
case 167:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='rosemary.zip,stages/SecretVillage.def';}
	if (rand==1) {mydiv='yagumo.zip,stages/SecretVillage.def';}
break;
case 168:
	rand=(Math.floor(Math.random()*5));
	if (rand==0) {mydiv='?..........,stages/ShaqFulab1.def';}
	if (rand==1) {mydiv='?..........,stages/ShaqFulab2.def';}
	if (rand==2) {mydiv='?..........,stages/ShaqFulab3.def';}
	if (rand==3) {mydiv='?..........,stages/ShaqFulab4.def';}
	if (rand==4) {mydiv='?..........,stages/ShaqFulab5.def';}
break;
case 169:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='femina30.zip,stages/ShockGalko.def';}
	if (rand==1) {mydiv='femina32.zip,stages/ShockGalko.def';}
break;
case 170:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ruili.zip,stages/ShockTrain.def';}
	if (rand==1) {mydiv='ruili.zip,stages/ShockTrain.def';}
break;
case 171:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='bebumryo.zip,stages/Slightly_Mad.def';}
	if (rand==1) {mydiv='bebumryo.zip,stages/Slightly_Mad.def';}
break;
case 172:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Barts.zip,stages/SlimSubwaySmash.def';}
	if (rand==1) {mydiv='Jack.zip,stages/SlimSubwaySmash.def';}
break;
case 173:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='marco.zip,stages/SnowRush.def';}
	if (rand==1) {mydiv='marco.zip,stages/SnowRush.def';}
break;
case 174:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Doparmin.zip,stages/SonicBlastJet.def';}
	if (rand==1) {mydiv='Walkyrie.zip,stages/SonicBlastJet.def';}
break;
case 175:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='hirezsonic.zip,stages/SonicSpecialStage.def';}
	if (rand==1) {mydiv='hirezsonic.zip,stages/SonicSpecialStage.def';}
break;
case 176:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='freedom.zip,stages/SpaceRocket.def';}
	if (rand==1) {mydiv='freedom.zip,stages/SpaceRocket.def';}
break;
case 177:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='gustavo.zip,stages/Stage005.def';}
	if (rand==1) {mydiv='gustavo.zip,stages/Stage005.def';}
break;
case 178:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Cammy.zip,stages/stageCammy.def';}
	if (rand==1) {mydiv='Cammy.zip,stages/stageCammy.def';}
break;
case 179:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='cvschunli.zip,stages/stageChunli.def';}
	if (rand==1) {mydiv='cvschunli.zip,stages/stageChunli.def';}
break;
case 180:
	rand=(Math.floor(Math.random()*3));
	if (rand==0) {mydiv='Ath-Chunli.zip,stages/stageDraco.def';}
	if (rand==1) {mydiv='Sexy_Arina.zip,stages/stageDraco.def';}
	if (rand==2) {mydiv='hotaru_bikini.zip,stages/stageDraco.def';}
break;
case 181:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/stageEtna.def';}
	if (rand==1) {mydiv='?..........,stages/stageEtna.def';}
break;
case 182:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Grizela.zip,stages/stageGrizela.def';}
	if (rand==1) {mydiv='Grizela.zip,stages/stageGrizela.def';}
break;
case 183:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Harmir.zip,stages/stageHarmir.def';}
	if (rand==1) {mydiv='Harmir.zip,stages/stageHarmir.def';}
break;
case 184:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ORCHID.zip,stages/stageHumio.def';}
	if (rand==1) {mydiv='Elektra.zip,stages/stageHumio.def';}
break;
case 185:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/stageMakoto.def';}
	if (rand==1) {mydiv='?..........,stages/stageMakoto.def';}
break;
case 186:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/stageScharlachrot.def';}
	if (rand==1) {mydiv='?..........,stages/stageScharlachrot.def';}
break;
case 187:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zako-Dan.zip,stages/streetcombat_tyrone.def';}
	if (rand==1) {mydiv='Zako-Dan.zip,stages/streetcombat_tyrone.def';}
break;
case 188:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Zinc.zip,stages/SubSpace.def';}
	if (rand==1) {mydiv='Zinc.zip,stages/SubSpace.def';}
break;
case 189:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='takezo.zip,stages/SubSpace1.def';}
	if (rand==1) {mydiv='genpaku.zip,stages/SubSpace1.def';}
break;
case 190:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Sailor_Mars.zip,stages/SubSpace2.def';}
	if (rand==1) {mydiv='Sailor_Jupiter.zip,stages/SubSpace2.def';}
break;
case 191:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='yoma.zip,stages/SubSpace3.def';}
	if (rand==1) {mydiv='maxine.zip,stages/SubSpace3.def';}
break;
case 192:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='mm_paperguy.zip,stages/SubSpace4.def';}
	if (rand==1) {mydiv='boon.zip,stages/SubSpace4.def';}
break;
case 193:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Bartman.zip,stages/SubSpace5.def';}
	if (rand==1) {mydiv='Bartman.zip,stages/SubSpace5.def';}
break;
case 194:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='raine.zip,stages/TailsAdventure1.def';}
	if (rand==1) {mydiv='raine.zip,stages/TailsAdventure1.def';}
break;
case 195:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kongou.zip,stages/TailsAdventure2.def';}
	if (rand==1) {mydiv='Captain_Kido.zip,stages/TailsAdventure2.def';}
break;
case 196:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='hashi.zip,stages/TerrariA.def';}
	if (rand==1) {mydiv='peketo.zip,stages/TerrariA.def';}
break;
case 197:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='viuda_negra.zip,stages/TerrariB.def';}
	if (rand==1) {mydiv='viuda_negra.zip,stages/TerrariB.def';}
break;
case 198:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='shar-makai.zip,stages/TerrariC.def';}
	if (rand==1) {mydiv='shar-makai.zip,stages/TerrariC.def';}
break;
case 199:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='gerdon.zip,stages/TerrorVision.def';}
	if (rand==1) {mydiv='saya.zip,stages/TerrorVision.def';}
break;
case 200:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='mokou.zip,stages/The_Fire_Prominence.def';}
	if (rand==1) {mydiv='mokou.zip,stages/The_Fire_Prominence.def';}
break;
case 201:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Konata.zip,stages/TheRuinsofMetro.def';}
	if (rand==1) {mydiv='Yukari.zip,stages/TheRuinsofMetro.def';}
break;
case 202:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='predator_W.zip,stages/TitanForest.def';}
	if (rand==1) {mydiv='predator_W.zip,stages/TitanForest.def';}
break;
case 203:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='blockhead.zip,stages/To-See-The-Light-of-Day.def';}
	if (rand==1) {mydiv='biped.zip,stages/To-See-The-Light-of-Day.def';}
break;
case 204:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='ROBO-KY.zip,stages/TowerofMorgul.def';}
	if (rand==1) {mydiv='ROBO-JAM.zip,stages/TowerofMorgul.def';}
break;
case 205:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/TowerofSuccubus.def';}
	if (rand==1) {mydiv='?..........,stages/TowerofSuccubus.def';}
break;
case 206:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='dc_lion.zip,stages/Transilvania.def';}
	if (rand==1) {mydiv='erim.zip,stages/Transilvania.def';}
break;
case 207:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Marco_nbc.zip,stages/TransporDrugs.def';}
	if (rand==1) {mydiv='Tarma.zip,stages/TransporTrain.def';}
break;
case 208:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Athena_WPr.zip,stages/Typically_me.def';}
	if (rand==1) {mydiv='ingrid.zip,stages/Typically_me.def';}
break;
case 209:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='DQ5-daughter.zip,stages/UluCity.def';}
	if (rand==1) {mydiv='DQ5-son.zip,stages/UluCityNF.def';}
break;
case 210:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='cless.zip,stages/VegetableValley1.def';}
	if (rand==1) {mydiv='kyle.zip,stages/VegetableValley2.def';}
break;
case 211:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='RacingMiku2014_EV.zip,stages/Viotoxica1.def';}
	if (rand==1) {mydiv='RacingMiku2014_EV.zip,stages/Viotoxica1.def';}
break;
case 212:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='armor.zip,stages/Viotoxica2.def';}
	if (rand==1) {mydiv='armor.zip,stages/Viotoxica2.def';}
break;
case 213:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='AOBA.zip,stages/Viotoxica3.def';}
	if (rand==1) {mydiv='Iari.zip,stages/Viotoxica3.def';}
break;
case 214:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='dios.zip,stages/Viotoxica4.def';}
	if (rand==1) {mydiv='dios.zip,stages/Viotoxica4.def';}
break;
case 215:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BlackRockShooter.zip,stages/Viotoxica5.def';}
	if (rand==1) {mydiv='BlackRockShooter.zip,stages/Viotoxica5.def';}
break;
case 216:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='aska-e.zip,stages/Weve-got-Shadowmans.def';}
	if (rand==1) {mydiv='VFKarin.zip,stages/Weve-got-Shadowmans.def';}
break;
case 217:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='SMOke&CLaudia8b.zip,stages/WhisperForest1.def';}
	if (rand==1) {mydiv='bbh.zip,stages/WhisperForest2.def';}
break;
case 218:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Fernando.zip,stages/WildSide.def';}
	if (rand==1) {mydiv='Fernando.zip,stages/WildSide.def';}
break;
case 219:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='cell.zip,stages/Wolfchild2.def';}
	if (rand==1) {mydiv='cell.zip,stages/Wolfchild2.def';}
break;
case 220:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='carol.zip,stages/World_of_insanity.def';}
	if (rand==1) {mydiv='MAY_X.zip,stages/World_of_insanity.def';}
break;
case 221:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Kurosawa.zip,stages/WotD.def';}
	if (rand==1) {mydiv='trident.zip,stages/WotD.def';}
break;
case 222:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='?..........,stages/XGranada.def';}
	if (rand==1) {mydiv='?..........,stages/XGranada.def';}
break;
case 223:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kira.zip,stages/ZeroCastle1.def';}
	if (rand==1) {mydiv='kira.zip,stages/ZeroCastle1.def';}
break;
case 224:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='KUROKO.zip,stages/ZeroCastle2.def';}
	if (rand==1) {mydiv='KUROKO.zip,stages/ZeroCastle2.def';}
break;
case 225:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='Hien.zip,stages/ZLeo_M1.def';}
	if (rand==1) {mydiv='Hiryuko.zip,stages/ZLeo_M1.def';}
break;
case 226:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='kureha.zip,stages/ZookHero_1.def';}
	if (rand==1) {mydiv='ageha.zip,stages/ZookHero_1.def';}
break;
case 227:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='BurningCirno.zip,stages/ZookHero_2.def';}
	if (rand==1) {mydiv='BurningCirno.zip,stages/ZookHero_2.def';}
break;
case 999:
	rand=(Math.floor(Math.random()*2));
	if (rand==0) {mydiv='';}
	if (rand==1) {mydiv='';}
break;
case 0:
mydiv='...'
}
//Write line and cache the new value
document.getElementById(2).innerText=""+previousValue+""+mydiv+""
previousValue = document.getElementById(2).innerText + "<br>";
};

function downloadFile() {
 const link = document.createElement("a");
 const content = previousValue;
 const file = new Blob([content], { type: 'text/plain' });
 link.href = URL.createObjectURL(file);
 link.download = "select.def";
 link.click();
 URL.revokeObjectURL(link.href);
};
